title: Kevin Xu Blog
description: Personal thoughts and tech insights
author: Kevin Xu
email: xkevinj@gmail.com
baseurl: "/github-blog"
url: "https://jkevinxu.github.io"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - .git/
  - .github/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/

# Pagination settings
paginate: 5
paginate_path: "/page:num/"

# Social links
twitter_username: 
github_username: JKevinXu
linkedin_username: 

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true

# Show future posts
future: true
